[package]
name = "pysephwasntavailable/remotepacketsizecounter"
version = "1.0.3"

license = "MIT"
authors = ["PysephWasntAvailable"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
exclude = ["**"]
